events {}

# Define which servers to include in the load balancing scheme.
#https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms-pt

http {

   upstream ping {
        server microservice-calc-main-ping-1:5000;
        server microservice-calc-main-ping-2:5000;
     }

    upstream calc{
        server microservice-calc-main-calc-1:5000;
    }

    upstream soma{
        server microservice-calc-main-soma-1:5000;
    }

    upstream sub{
        server microservice-calc-main-sub-1:5000;
    }

    upstream mult {
        server mult1:5000 weight=3;
        server mult2:5000 weight=1;
        server mult3:5000 backup;
    }

# This server accepts all traffic to port 80 and passes it to the upstream.
     server {
         listen 80;

         server_name app.com;

         location /ping {
              proxy_pass http://ping;
         }

         location /calc {
              proxy_pass http://calc;
         }

         location /soma {
              proxy_pass http://soma;
         }

         location /sub {
              proxy_pass http://sub;
         }

         location /mult {
              proxy_pass http://mult;
              proxy_connect_timeout 2s;
         }
     }
}